# Generated by Django 2.2 on 2019-04-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20190428_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='add_date',
        ),
    ]
